### ISSUE TITLE
Possible issue with material visibility in Yafaray

### ISSUE THREAD

**Issue by Micheus** [DavidBluecame/wings#11]
Hi David

I'm going to put this here to not pollute the libYafaray with a possible not real problem.

I just added the _cast shadows_  and _visibility_ properties to the Yafaray plugin and by testing I notice there is a difference between two visibility settings: _Shadow Only_ and _Invisible_

The shadows it self is OK, my concern is about the _hole_ left by making the object/material invisible. 
For the _Shadow Only_ I was expecting the object get its internal faces rendered just like in _Invisible_ option - not a black hole.

Should it really look like this or is it a "bug"?
![yafaray-material-visibility](https://user-images.githubusercontent.com/365243/113661029-b8c51680-967b-11eb-9317-eef36063d36d.png)

**Comment by DavidBluecame** [comment]
Hello, Micheus. I don't think this is a bug. In the example with "Shadow only", the green cylinder is invisible (correct) and it's casting shadows both on the floor *and* at the top of the bottom gray cylinder (also correct). Therefore the light cannot get inside the bottom gray cylinder.

**Comment by DavidBluecame** [comment]
To achieve something in between both the "Shadow only" and the "Invisible" examples, so the top green cylinder is invisible it casts shadows only on the floor but not on the top of the gray cylinder, you could create a scene composed of two light sources:

* Light source one: normal, the same you have now
* Light source two: a different light, maybe a different type of light and/or in a different angle, with the parameter "cast_shadows" set to false. In theory a light source with cast_shadows=false should not cast shadows and can be used to "fill" with light the inside of that gray cylinder.

Keep in mind that, the moment you start using these tweaks with different visibility/shadow casting options, the scene is no longer "physically realistic" and therefore all the necessary tweaks to obtain the desired results are up to the user. In some cases it can be complex and difficult to get a certain "non physically realistic" result.

**Comment by Micheus** [comment]
> Hello, Micheus. I don't think this is a bug. In the example with "Shadow only", the green cylinder is invisible (correct) and it's casting shadows both on the floor _and_ at the top of the bottom gray cylinder (also correct). Therefore the light cannot get inside the bottom gray cylinder.

Understood now. The black hole is in fact the shadow of the invisible piece just above it.

> Keep in mind that, the moment you start using these tweaks with different visibility/shadow casting options, the scene is no longer "physically realistic" and therefore all the necessary tweaks to obtain the desired results are up to the user. In some cases it can be complex and difficult to get a certain "non physically realistic" result.

Sure. 

Thanks for the feedback and help to understand what I was not seeing. 🙂
