### ISSUE TITLE
Volume and light portal objects: doubts after visibility and shadows addition

### ISSUE THREAD

**Issue by Micheus** [DavidBluecame/wings#12]
Hi David

After I have added the these items to the plugin the user **oort** came with a couple of questions which I have no idea about the answer since they are Yafaray specific ones. So, I hope you could help me with that. 🙂 

Here is his comment:

> _I did some testing today. The "Visibility" setting does work with "Mesh" and "Mesh Light" Object Types._
> 
> _From what I have seen in my tests, the setting does NOT do anything for "Volume" Object Types. No negative impact but Volume objects still produce shadows. Maybe this feature is not supported with Volumes in YafaRay???_
> 
> _"Light Portal" objects do not produce shadows and it seems they never did. I played with light portals a bit more today while testing the updated plugin and I am not sure that they are even working. Maybe they never worked??? I will have to do more testing of light portals. They are supposed to focus Ambient light (HDRI) coming through windows in a room. Here is a video that describes how light portals are supposed to work in Cycles using Blender... Light Portals explained_

also, I already pushed the changes to **dgud** _master_ repository. Should I push it to your repository too, or do you intend to update your master branch with the **dgud**'s one. (I believe this would be the the safest way to keep them sync - I use to do that)

Thanks for your attention

**Comment by DavidBluecame** [comment]
Hello, Micheus.

Please do the updates in your repos, I'll pull them from there if I had to
make any suggested changes myself and would send a pull request to your
repos in that case.

About the visibility setting for Mesh Light and volumes, I would have to
check, but it's possible that it never actually worked.

Light portals are supposed to be just that, not objects casting shadows. As
far as I understand they just bring the background into the scene through
the surface of the portal object.

**Comment by Micheus** [comment]
Thank you for the answer.
Is that OK if in the future I use this channel to take off any other doubts?

**Comment by DavidBluecame** [comment]
Hi, @Micheus Yes, it's fine. Thanks!
