### ISSUE TITLE
Light Portals - Is that still available?

### ISSUE THREAD

**Issue by Micheus** [DavidBluecame/wings#13]
David, while **oort** has been testing the visibility and shadows additions to the plugin he noticed the LightPortals property (object_type) seems to not be working correctly.

Do you have any xml file as an example so we can evaluate what is going wrong with our scene setup?
I tried to find something online, but I failed.

**Comment by Micheus** [comment]
Ok. Thanks for your feedback at the Wings3D forum.

Something oort suggested and I added was to set a static value (256) to _mesh **type**_ in the _LightPortal_ object in order to not get it visible, but emitting light - the _Visibility_ property seems to not help with that:
`println(F, "<mesh id=\"~w\" vertices=\"~w\" faces=\"~w\" has_uv=\"~s\" type=\"256\">", [Id,length(Vs), length(Fs), HasUV]),`

Do you have any tip about that or we can consider that a valid workaround?

**Comment by DavidBluecame** [comment]
Hello, I think that's correct.
In fact it seems to be what the Blender exporter is already doing:

```
def writeBGPortal(self, obj, matrix):

        self.yi.printInfo("Exporting Background Portal Light: {0}".format(obj.name))

        # Generate unique object ID
        ID = self.yi.getNextFreeID()

        self.yi.paramsClearAll()
        self.yi.paramsSetInt("obj_pass_index", obj.pass_index)
        self.yi.paramsSetString("type", "bgPortalLight")
        self.yi.paramsSetFloat("power", obj.bgp_power)
        self.yi.paramsSetInt("samples", obj.bgp_samples)
        self.yi.paramsSetInt("object", ID)
        self.yi.paramsSetBool("with_caustic", obj.bgp_with_caustic)
        self.yi.paramsSetBool("with_diffuse", obj.bgp_with_diffuse)
        self.yi.paramsSetBool("photon_only", obj.bgp_photon_only)
        self.yi.createLight(obj.name)

        obType = 256  # Makes object invisible to the renderer (doesn't enter the kdtree)
```

**Comment by Micheus** [comment]
Great. Thanks.
